### ISSUE TITLE
Kindle Fire?

### ISSUE THREAD

**Issue by Shpigford** [jistr/mobvious#3]
How would I get a Kindle Fire to be recognized as a tablet? It's currently recognized as "desktop"

**Comment by johncant** [comment]
I'm guessing you're using MobileESP.
Either:
(1) Ask the authors of MobileESP to get it to work with Kindle Fire, or code it yourself
(2) Insert your own strategy before MobileESP to detect kindle fires as :tablet

**Comment by Shpigford** [comment]
I'm using Mobvious...which uses its own custom mobileesp_converted gem...which is maintained by jistr. So, this is me asking the author to get it to work with Kindle Fire. :)

And me posting here is asking how to code it myself. I'm asking because _I don't know how to do it_.

**Comment by johncant** [comment]
Looks like the MobileESP guys fixed their Kindle Fire support back in April: http://blog.mobileesp.com/?p=287 , whereas mobileesp_converted was last updated back in March.

@jistr generated mobileesp_converted from MobileESP using a vim script which is included, so you could try regenerating it.

**Comment by jistr** [comment]
Hi guys, sorry for not reacting on this for some time, I have a lot of work elsewhere.

Yes, what John is saying is correct. I will probably try to regenerate mobileesp_converted myself soon, but cannot really guarantee any time frame.

**Comment by jistr** [comment]
I regenerated mobileesp_converted to match current MobileESP Java library and released v0.2.1, but it still doesn't detect Kindle Fire as tablet. I'll not fix this because the aim is to mirror MobileESP to Ruby, not fork it and diverge the codebases.

However, I think the problem can be solved by writing custom detection procedure similar to the original one (https://github.com/jistr/mobvious/blob/master/lib/mobvious/strategies/mobileesp.rb#L17-22) and passing it as an argument to MobileESP strategy. Worst case is you'll have to peek inside user agent string by yourself, but it should be doable.

**Comment by jistr** [comment]
As a side note, I recommend using responsive web design over user agent detection whenever possible now. There is growing number of devices with various sizes and properties, and it's increasingly hard to draw borderlines between computers / tablets / phones (I've heard the word "phablet" already :) ), which sort of goes against any user-agent based approach. Responsive design allows you to tailor user experience precisely to the device and does not attempt to categorize, which is a superior solution for upcoming years, I believe. It has some disadvantages too, but usually they are outweighed by advantages pretty well, especially since mobile bandwidth is year by year less of an issue.

**Comment by jistr** [comment]
Back to writing custom detection procedure -- if you wonder what methods can you call on the `mobileesp` object being passed into the procedure, here is how the object's class looks like: https://github.com/jistr/mobileesp_converted/blob/master/lib/mobileesp_converted/user_agent_info.rb#L79
